articles/urls.py
from django.urls import path
from . import views

app_name = "articles"

urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
    path("create/", views.ArticleCreateView.as_view(), name="article-create"),
    path("<int:pk>/", views.ArticleDetailView.as_view(), name="article-detail"),
    path("delete/<int:pk>/", views.ArticleDetailView.as_view(), name="article-delete"),
    path("edit/<int:pk>", views.ArticleDetailView.as_view(), name="article-update"),
    #path("edit/<int:pk>/", views.ArticleUpdateView.as_view(), name="article-update"),
    path("meta/", views.ArticleMetaView.as_view(), name="article-meta"),
    path("fetch-from-rss/", views.FetchArticlesFromRSS.as_view(), name="fetch-from-rss"),
]

blog/urls.py
from django.urls import path
from . import views

app_name = "blog"

urlpatterns = [
    path("", views.BlogView.as_view(), name="home"),
    path("<int:pk>/", views.BlogDetailView.as_view(), name="blog_detail"),
    path("create/", views.BlogCreateView.as_view(), name="create_blog"),
    path("edit/<int:pk>", views.BlogUpdateView.as_view(), name="update_blog"),
    path("delete/<int:pk>", views.BlogDeleteView.as_view(), name="delete_blog"),
]

techstructive_blog/urls.py
from django.contrib import admin
from django.urls import path, include
from .routers import router
from articles import views as article_views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("user/", include("user.urls", namespace="users")),
    path('accounts/', include('django.contrib.auth.urls')),
    path("article/", include("articles.urls", namespace="articles")),
    path("", include("blog.urls", namespace="blog")),
    path(r'watchman/', include('watchman.urls')),
    #path("api/", include(router.urls)),
]

articles/models.py
from user.models import TimeStampedModel
from django.utils.translation import gettext_lazy as _
from django.urls import reverse
from django.db import models
from blog.models import Blog
from user.models import User



class Tags(TimeStampedModel):
    ...


class Series(TimeStampedModel):
    ...


class Article(TimeStampedModel):
    class Article_Status(models.TextChoices):
        DRAFT = (
            "DRAFT",
            _("Draft"),
        )
        PUBLISHED = (
            "PUBLISHED",
            _("Published"),
        )

    title = models.CharField(max_length=128)
    description = models.CharField(max_length=256)
    content = models.TextField(default="", null=False, blank=False)
    status = models.CharField(
        max_length=16,
        choices=Article_Status.choices,
        default=Article_Status.DRAFT,
    )
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE, null=True, blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="author")

    def __str__(self):
        return self.title

    def get_absolute_url(self):      
        return reverse('articles:article-detail', args=[str(self.id)])

articles/forms.py
from django import forms
from blog.models import Blog
from .models import Article


class ArticleForm(forms.ModelForm):
    def __init__(self, user, *args, **kwargs):
        super(ArticleForm, self).__init__(*args, **kwargs)
        self.fields['blog'].queryset = Blog.objects.filter(authors=user)

    class Meta:
        model = Article
        exclude = (
            "created",
            "updated",
            "author",
        )
        widgets = {
            "title": forms.TextInput(
                attrs={
                    "class": "form-control",
                    "style": "max-width: 450px; align: center;",
                    "placeholder": "Title",
                }
            ),
            "description": forms.TextInput(
                attrs={
                    "class": "form-control",
                    "style": "max-width: 900px; ",
                    "placeholder": "Description",
                }
            ),
            "content": forms.Textarea(
                attrs={
                    "class": "form-control post-body",
                    "id": "text-content",
                    "style": "max-width:900px;",
                    "hx-post": "/article/meta/",
                    "placeholder": "Content",
                }
            ),
            "blog": forms.Select(
                attrs={
                    "class": "form-control",
                    "placeholder": "Blog Publication",
                }
            ),
        }

articles/views.py
from operator import concat
from re import T
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse, QueryDict
from django.shortcuts import render
from rest_framework import request
from blog.models import Blog
from django.contrib import messages
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse
from django.views import View
import frontmatter
from django.shortcuts import redirect
import feedparser
import re


from .models import Article
from .forms import ArticleForm


class ArticleCreateView(CreateView):
    model = Article
    form_class = ArticleForm

    def get_form_kwargs(self):
        kwargs = super(ArticleCreateView, self).get_form_kwargs()
        kwargs.update({'user': self.request.user})
        return kwargs

    def form_valid(self, form):
        form.instance.author = self.request.user
        if form.instance.blog:
            blog = form.instance.blog
            if blog.authors.id == self.request.user.id:
                form.instance.blog = blog
            else:
                form.instance.blog = None
        obj = form.save()
        messages.add_message(self.request, messages.SUCCESS, 'Your article has been saved!')
        blog = Blog.objects.get(authors=self.request.user)
        context = {'article': obj, 'blog': blog}
        return render(self.request, "articles/partials/article-detail.html",context)


class HomeView(LoginRequiredMixin, View):
    model = Article

    template_name = "articles/index.html"
    def get(self, request):
        articles = Article.objects.filter(author=request.user)
        #blog = Blog.objects.get(authors=request.user)
        context = {'articles': articles}#, 'blog': blog}
        return render(request, "articles/index.html", context)

    def get_context_data(self, *, object_list=None, **kwargs):
        articles = Article.objects.filter(author=self.request.user)
        return super().get_context_data(articles=articles, **kwargs)


class ArticleDetailView(LoginRequiredMixin, View):
    model = Article

    def get_form_kwargs(self):
            kwargs = super(ArticleForm, self).get_form_kwargs()
            kwargs.update({'user': self.request.user})
            return kwargs
    def get(self, request, pk, *args, **kwargs):
        article = Article.objects.get(id=pk)
        return render(self.request, 'articles/article_detail.html', {'article': article})

    def delete(self, request, pk, *args, **kwargs):
        Article.objects.get(id=pk).delete()
        articles = Article.objects.filter(author=self.request.user)
        return render(request, "articles/partials/article-list.html", {'articles': articles})
    
    def put(self, request, pk, *args, **kwargs):
        article = Article.objects.get(id=pk)
        form = ArticleForm(request.user, instance=article, data=QueryDict(request.body))
        if form.is_valid():
            article = form.save()
            return render(self.request, "articles/partials/article-detail.html", {'article': article})

    def post(self, request, pk, *args, **kwargs):
        article = Article.objects.get(id=pk)
        form = ArticleForm(request.user, instance=article)
        context = {
            'form': form,
            'article': article,
        }
        return render(request, 'articles/partials/update.html', context)

class ArticleUpdateView(UpdateView):
    model = Article
    form_class = ArticleForm
    template_name = "articles/edit_article.html"

class ArticleMetaView(View):
    model = Article

    def post(self, request, *args, **kwargs):
        import json
        data = json.loads(json.dumps(dict(request.POST)))
        loaded_frontmatter = frontmatter.loads(data['content'][0])
        if dict(loaded_frontmatter):
            article_title = loaded_frontmatter['title']
            article_description = loaded_frontmatter['description']
            form = ArticleForm(request.user, initial={'title': article_title, 'description': article_description, 'content': loaded_frontmatter.content})
            context = {'form': form}
            if Article.objects.filter(title=article_title):
                article = Article.objects.filter(title=article_title).last()
                context['article'] = article
                return render(request, 'articles/edit_article.html', context)
            return render(request, 'articles/article_form.html', context)

        article_list = Article.objects.filter(title=data['title'][0])

        if article_list:
            article = article_list.last()
            form = ArticleForm(request.user, data=request.POST)
            context = {'form': form}
            context['article'] = article
            return render(request, 'articles/edit_article.html', context)
        form = ArticleForm(request.user, data=request.POST)
        context = {'form': form}
        return render(request, 'articles/article_form.html', context)

    def get_form_kwargs(self):
            kwargs = super(ArticleMetaView, self).get_form_kwargs()
            kwargs.update({'user': self.request.user})
            return kwargs

class FetchArticlesFromRSS(View):
    def get(self, request):
        link = "https://www.meetgor.com/rss"
        feed = feedparser.parse(link)
        article_list = Article.objects.values_list('title', flat=True)
        for post in feed.entries:
            print(post.title)
            if not post.title in article_list:
                article = Article()
                article.title = post['title']
                content = post['content'][0]['value']
                #content = content.replace(r'<div class="prevnext">(.*?)</div>', "")
                prevnext = re.findall(r'<div class="prevnext">(.*?)</div>', content)
                prevnext += re.findall(r'<a class="next"(.*?)</a>', content)
                for i in prevnext:
                    content = content.replace(i, "")
                article.content = content
                article.description = post['summary']
                article.status = "PUBLISHED"
                article.author = self.request.user
                article.save()

        return redirect('/article')
        

templates/articles/partials/article-delete.html
    <script>
      document.body.addEventListener('htmx:configRequest', (event) => {
        event.detail.headers['X-CSRFToken'] = '{{ csrf_token }}';
      })
    </script>
<div class="container pt-5">
  <form method="post" >
  {% csrf_token %}
    <button
      hx-delete="{% url 'articles:article-delete' article.id %}"
      hx-confirm="Are you sure, You want to delete this article?"
      type="submit"
      >
      Delete
    </button>
  </form>
</div>

templates/articles/partials/article-detail.html
{% load markdown_article %}
<div hx-target="this" hx-swap="outerHTML">
<div class="container pt-5">
    <form method="post" novalidate>
        {% csrf_token %}
        {% for field in form.visible_fields %}
            <div class="form-group">
                <label for="{{ field.id_for_label }}">{{field.label}}</label>
                  {{ field }}
                {% for error in field.errors %}
                    <span class="help-block" style="color:red">{{error}}</span>
                {% endfor %}
            </div>
        {% endfor %}
        <div>
       <button 
         hx-post="{% url 'articles:article-update' article.id %}"
         type="submit" class="btn btn-success btn-sm">
         Update
       </button>
        </div>
    </form>
</div>
<div id="article-detail">
  {% include 'articles/partials/article-delete.html' %}
  <h2>{{ article.title }}</h2>
    <h3>{{ article.description }}</h3>
    <p>{{ article.content|convert_markdown|safe|linebreaks }}</p>
</div>
</div>

templates/articles/partials/article-list.html
<ul id="article-list">
  {% for article in articles %}
    <li>
      <a href="{% url 'articles:article-detail' article.id %}">
        {{ article.title }}
      </a>
    </li>
  {% endfor %}
</ul>

templates/articles/partials/update.html
{% load markdown_article %}
<div hx-target="this" hx-swap="outerHTML">
<div class="container pt-5">
    <form>
        {% csrf_token %}
        {% for field in form.visible_fields %}
            <div class="form-group">
                <label for="{{ field.id_for_label }}">{{field.label}}</label>
                {# {% if field.label == 'Content' %} #}
                {#  <p>{{ field.value|convert_markdown|safe|linebreaks }}</p> #}
                {# {% endif %} #}
                  {{ field }}
                {% for error in field.errors %}
                    <span class="help-block" style="color:red">{{error}}</span>
                {% endfor %}
            </div>
        {% endfor %}
        <div>
         <button 
           hx-put="{% url 'articles:article-update' article.id %}"
           type="submit" class="btn btn-success btn-sm">
           Update
         </button>
        </div>
    </form>
</div>
</div>