blog/urls.py
from django.urls import path
from . import views

app_name = "blog"

urlpatterns = [
    path("", views.BlogView.as_view(), name="home"),
    path("<int:pk>/", views.BlogDetailView.as_view(), name="blog_detail"),
    path("create/", views.BlogCreateView.as_view(), name="create_blog"),
    path("edit/<int:pk>", views.BlogUpdateView.as_view(), name="update_blog"),
    path("delete/<int:pk>", views.BlogDeleteView.as_view(), name="delete_blog"),
]

techstructive_blog/urls.py
from django.contrib import admin
from django.urls import path, include
from .routers import router
from articles import views as article_views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("user/", include("user.urls", namespace="users")),
    path('accounts/', include('django.contrib.auth.urls')),
    path("article/", include("articles.urls", namespace="articles")),
    path("", include("blog.urls", namespace="blog")),
    path(r'watchman/', include('watchman.urls')),
    #path("api/", include(router.urls)),
]

blog/models.py
from django.db import models

from user.models import User


class Blog(models.Model):
    name = models.CharField(max_length=128)
    description = models.TextField()
    authors = models.ForeignKey(User, on_delete=models.CASCADE, related_name="authors")
    
    def __str__(self):
        return self.name

blog/forms.py
from django import forms
from .models import Blog


class BlogForm(forms.ModelForm):
    class Meta:
        model = Blog
        exclude = (
            "authors",
            "created",
            "updated",
        )
        widgets = {
            "name": forms.TextInput(
                attrs={
                    "class": "form-control",
                    "style": "max-width: 300px;",
                    "placeholder": "Name",
                }
            ),
            "description": forms.TextInput(
                attrs={
                    "class": "form-control",
                    "style": "max-width: 300px;",
                    "placeholder": "description",
                }
            ),
        }

blog/views.py
from .models import Blog
from articles.models import Article
from .serializers import BlogSerializer
from .forms import BlogForm
from django.shortcuts import render
from django.views import View
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from rest_framework import mixins, viewsets
from rest_framework.views import APIView
from django.contrib.auth.mixins import LoginRequiredMixin

class BlogViewSet(viewsets.ModelViewSet):
    queryset = Blog.objects.all()
    serializer_class = BlogSerializer


class BlogView(LoginRequiredMixin, View):
    model = Blog
    template_name = "base.html"

    def get(self, request, *args, **kwargs):
        context = {}
        blog = Blog.objects.filter(authors=request.user)
        context["blogs"] = blog
        context["articles"] = Article.objects.filter(blog=blog)
        return render(request, "blog/blog_login.html", context)

    def post(self, request, *args, **kwargs):
        context = {}
        blog_id = request.POST.get('blog')
        blog = Blog.objects.get(id=blog_id)
        articles = Article.objects.filter(blog=blog)
        context = {'blog': blog, 'articles': articles}
        return render(request, "base.html", context)


class BlogSecureView:

    model = Blog

    def dispatch(self, request, *args, **kwargs):
        handler = super().dispatch(request, *args, **kwargs)
        return handler


class BlogListView(BlogView, ListView):
    """View to list all Blogs."""

    template_name = "blog/index.html"


class BlogDetailView(BlogSecureView, DetailView):
    """View to list the details for a Blog."""

    template_name = "blog/blog_detail.html"


class BlogCreateView(CreateView):
    """View to create a new Blog"""

    form_class = BlogForm
    template_name = "blog/create_blog.html"
    success_url = "/blog"

    def form_valid(self, form):
        form.instance.authors = self.request.user
        return super().form_valid(form)


class BlogUpdateView(BlogSecureView, UpdateView):
    """View to update an Blog"""

    form_class = BlogForm
    template_name = "blog/edit_blog.html"
    success_url = "/blog"


class BlogDeleteView(BlogSecureView, DeleteView):
    """View to delete an Blog"""

    template_name = "blog/delete_blog.html"
    success_url = "/blog"

templates/blog/blog_detail.html
{% extends 'base.html' %}
{% block body %}
  <h2>{{ blog.name }}</h2>
  <a href="{% url 'blog:update_blog' blog.id %}"><button>Edit</button></a>
  <a href="{% url 'blog:delete_blog' blog.id %}"><button>Delete</button></a>
  <h3>{{ blog.description }}</h3>
{% endblock %}

templates/blog/blog_login.html
{% extends 'base.html' %}
{% block body %}
<div hx-target="this" hx-swap="outerHTML">
<form >
  <select name="blog" id="blog-options">
  {% for blog in blogs %}
    <option value="{{ blog.id }}">{{ blog.name }}</option>
  {% endfor %}
</select>
<button 
  hx-post="."
  type="submit">Submit</button>
</form>
</div>
{% endblock %}

templates/blog/create_blog.html
{% extends 'base.html' %}
{% block body %}
<div class="container pt-5">
    <form method="post" novalidate>
        {% csrf_token %}
        {% for field in form.visible_fields %}
            <div class="form-group">
                <label for="{{ field.id_for_label }}">{{field.label}}</label>
                {{field}}
                {% for error in field.errors %}
                    <span class="help-block" style="color:red">{{error}}</span>
                {% endfor %}
            </div>
        {% endfor %}
        <div>
            <button type="submit" class="btn btn-success">Save</button>
            <a href="{% url 'blog:home' %}" class="btn btn-default">Cancel</a>
        </div>
    </form>
</div>
{% endblock %}

templates/blog/delete_blog.html
{% extends 'base.html' %}
{% block body %}
<div class="container pt-5">
    <form method="post" novalidate>
        {% csrf_token %}
        <p>Are you sure you want to delete the Blog<b>{{ object.name }}</b>?</p>
        <input type="submit" value="confirm">
    </form>
  <a href="{% url 'blog:blog_detail' object.id %}"><button>Back</button></a>
</div>
{% endblock %}

templates/blog/edit_blog.html
{% extends 'base.html' %}
{% block body %}
<div class="container pt-5">
  <a href="{% url 'blog:blog_detail' object.id %}"><button>Back</button></a>
    <h3>Update Blog</h3>
    <form method="post" novalidate>
        {% csrf_token %}
        {% for field in form.visible_fields %}
            <div class="form-group">
                <label for="{{ field.id_for_label }}">{{field.label}}</label>
                {{field}}
                {% for error in field.errors %}
                    <span class="help-block" style="color:red">{{error}}</span>
                {% endfor %}
            </div>
        {% endfor %}
        <div>
            <button type="submit" class="btn btn-success">Update</button>
        </div>
    </form>
</div>
{% endblock %}

templates/blog/htmx_articlelist.html
{% extends 'base.html' %}
{% block body %}
    <!-- htmx -->
    <script src="https://unpkg.com/htmx.org@1.6.1/dist/ext/client-side-templates.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/nunjucks/3.0.1/nunjucks.min.js" integrity="sha512-IIuR+Zp8wvP0dxNcSsRPoL7SXzP1kGmosDtcU7f6cPObZ9F5Ze/icFSRH/SqigP468jGwDm2XOE0/gSGm/cTBw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
</head>
    <div hx-ext="client-side-templates"
         hx-trigger="load"
         hx-get="/api/blog" 
         hx-target="#list"
         hx-swap="outerHTML"
         nunjucks-template="articlelist"
      ></div>

      <script id="articlelist" type="nunjucks">
        {% verbatim %}
        {% for article in articles %}
          <li>
           <a href="/api/blog/{{ article.id }}"><h2>{{article.title}}</h2></a>
            <p>{{article.description}}</p>
          </li>
        {% endfor %}
        {% endverbatim %}
      </script>
      <ul id="list"></ul>
    <script>
htmx.defineExtension('client-side-templates', {
  transformResponse : function(text, xhr, elt) {
    var nunjucksTemplate = htmx.closest(elt, "[nunjucks-template]");
    if (nunjucksTemplate) {
      var data = {
        articles: JSON.parse(text).map((item) => {
          return item;
        })
      };

      var templateName = nunjucksTemplate.getAttribute('nunjucks-template');
      var template = htmx.find('#' + templateName);
      return nunjucks.renderString(template.innerHTML, data);
    }
    return text;
  }
});
    </script>
{% endblock %}

templates/blog/index.html
{% extends 'base.html' %}
{% block body %}
<a href="{% url 'blog:create_blog' %}" ><button>Create</button></a>
<ul>
  {% for blog in blogs %}
  <li>
    <a href="{% url 'blog:blog_detail' blog.id %}"><h2>{{ blog.name }}</h2></a>
    <p>{{ blog.description }}</p>
  </li>
  {% endfor %}
</ul>
{% endblock %}