articles/urls.py
from django.urls import path
from . import views

app_name = "articles"

urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
    path("create/", views.ArticleCreateView.as_view(), name="article-create"),
    path("<int:pk>/", views.ArticleDetailView.as_view(), name="article-detail"),
    path("delete/<int:pk>/", views.ArticleDetailView.as_view(), name="article-delete"),
    path("edit/<int:pk>", views.ArticleDetailView.as_view(), name="article-update"),
    #path("edit/<int:pk>/", views.ArticleUpdateView.as_view(), name="article-update"),
    path("meta/", views.ArticleMetaView.as_view(), name="article-meta"),
    path("fetch-from-rss/", views.FetchArticlesFromRSS.as_view(), name="fetch-from-rss"),
]

blog/urls.py
from django.urls import path
from . import views

app_name = "blog"

urlpatterns = [
    path("", views.BlogView.as_view(), name="home"),
    path("<int:pk>/", views.BlogDetailView.as_view(), name="blog_detail"),
    path("create/", views.BlogCreateView.as_view(), name="create_blog"),
    path("edit/<int:pk>", views.BlogUpdateView.as_view(), name="update_blog"),
    path("delete/<int:pk>", views.BlogDeleteView.as_view(), name="delete_blog"),
]

techstructive_blog/urls.py
from django.contrib import admin
from django.urls import path, include
from .routers import router
from articles import views as article_views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("user/", include("user.urls", namespace="users")),
    path('accounts/', include('django.contrib.auth.urls')),
    path("article/", include("articles.urls", namespace="articles")),
    path("", include("blog.urls", namespace="blog")),
    path(r'watchman/', include('watchman.urls')),
    #path("api/", include(router.urls)),
]

user/urls.py
from django.urls import path

from user.views import (
    register,
)

app_name = "user"
urlpatterns = [
    path("register/", view=register, name='register'),
]

templates/base.html
{% load static i18n %}<!DOCTYPE html>
{% get_current_language as LANGUAGE_CODE %}
<html lang="{{ LANGUAGE_CODE }}">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}Django Blog{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Latest compiled and minified Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.1.3/css/bootstrap.min.css" integrity="sha512-GQGU0fMMi238uA+a/bdWJfpUGKUkBdgfFdgBm72SUQ6BeyWjoY/ton0tEjH+OSH9iP4Dfh+7HM0I9f5eR0L/4w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="{% static 'css/style.css' %}">
    <!-- This file stores project-specific CSS -->
    {# Placed at the top of the document so pages load faster with defer #}
      <script defer src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.1.3/js/bootstrap.min.js" integrity="sha512-OvBgP9A2JBgiRad/mM36mkzXSXaJE9BEIENnVEmeZdITvwT09xnxLtT4twkCa8m/loMbPHsvPl0T8lRGVBwjlQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
  <script src="https://unpkg.com/htmx.org@1.8.0"></script>
  </head>
  <body hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}' >
<div class="mb-1">
      <nav class="navbar navbar-expand-md navbar-light bg-light">
        <div class="container-fluid">
          <button class="navbar-toggler navbar-toggler-right" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          {% if blog.name %}
          <a class="navbar-brand" href="{% url 'blog:home' %}">{{ blog.name }}</a>
          {% else %}
            <a class="navbar-brand" href="{% url 'blog:home' %}">Django Blog </a>
          {% endif %}

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
      {% if request.user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'blog:home' %}">Blog</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'articles:home' %}">My Articles</a>
        </li>
        <li class="nav-item">
          {# URL provided by django-allauth/account/urls.py #}
          <a class="nav-link" href="{% url 'logout' %}?next={{request.path}}">{% translate "Sign Out" %}</a>
        </li>
      {% else %}
      <li class="nav-item">
        {# URL provided by django-allauth/account/urls.py #}
        <a id="sign-up-link" class="nav-link" href="{% url 'user:register' %}">{% translate "Sign Up" %}</a>
      </li>
      {% endif %}
        <li class="nav-item">
          {# URL provided by django-allauth/account/urls.py #}
          <a id="log-in-link" class="nav-link" href="{% url 'login' %}">{% translate "Sign In" %}</a>
        </li>
        </ul>
        </div>
      </div>
    </nav>

    </div>

    <div class="container">

      {% block body %}
      {% if user.is_authenticated %}
      <h2>{{ blog.name }}</h2>
      <a href="{% url 'articles:article-create' %}"><button class="btn">Create</button></a>
        <ul id="article-list">
          {% for article in articles %}
            <li>
              <a href="{% url 'articles:article-detail' article.id %}">
                {{ article.title }}
              </a>
            </li>
          {% endfor %}
        </ul>
      {% endif %}
      {% endblock %}

  </body>
</html>